spring:
    datasource:
        url: jdbc:mysql://localhost:3306/wiki_clickstream?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        username: root
        password: colt1911
        driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
        database: 0
        host: localhost
        port: 6379

mybatis:
    mapper-locations: "classpath:mybatis/*Mapper.xml"
