spring:
    datasource:
        url: jdbc:mysql://localhost:3306/wiki_clickstream?useUnicode=true&characterEncoding=utf8
        username: root
        password: colt1911
        driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    mapper-locations: "classpath:mybatis/*Mapper.xml"
